name: Generate Snk 

on:
  workflow_dispatch:
  push:
    branches:
    - main
  schedule:
    - cron: "0 */6 * 3,4,5 *" # Runs at 0 minutes past the hour, every 6 hours, only in March, April, and May.
    - cron: "0 */6 * 6,7,8 *" # Runs at 0 minutes past the hour, every 6 hours, only in June, July, and August.
    - cron: "0 */6 * 9,10,11 *" # Runs at 0 minutes past the hour, every 6 hours, only in September, October, and November.
    - cron: "0 */6 * 12,1,2 *" # Runs at 0 minutes past the hour, every 6 hours, only in December, January, and February.

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Set current month as environment variable
        run: echo "CRL_MONTH=$(date +'%m')" >> $GITHUB_ENV

      # winter theme
      - name: generate github-contribution-grid-snake.svg
        if: github.event.schedule == '0 */6 * 12,1,2 *' || ((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && contains('12 01 02', env.CRL_MONTH))
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ vars.COMMIT_USERNAME }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#5A639C&color_dots=#F0F3FF,#A5D7E8,#576CBC,#19376D,#0B2447
            dist/github-contribution-grid-snake-dark.svg?color_snake=#A5D7E8&color_dots=#304463,#5A639C,#7776B3,#9B86BD,#E2BBE9

      # spring theme
      - name: generate github-contribution-grid-snake.svg
        if: github.event.schedule == '0 */6 * 3,4,5 *' || ((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && contains('03 04 05', env.CRL_MONTH))
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ vars.COMMIT_USERNAME }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#8C7676&color_dots=#F4EEEE,#FEE3EC,#F9C5D5,#F999B7,#F2789F
            dist/github-contribution-grid-snake-dark.svg?color_snake=#FA7070&color_dots=#8C7676,#91DDCF,#99F0CA,#C9FDD7,#FDFFE7

      # summer theme
      - name: generate github-contribution-grid-snake.svg
        if: github.event.schedule == '0 */6 * 6,7,8 *' || ((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && contains('06 07 08', env.CRL_MONTH))
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ vars.COMMIT_USERNAME }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#EF5A6F&color_dots=#F7F9F2,#FDFFBC,#FFEEBB,#FFDCB8,#FFC1B6
            dist/github-contribution-grid-snake-dark.svg?color_snake=#AEE6E6&color_dots=#211f20,#534E52,#965D62,#C7956D,#F2D974

      # Fall theme
      - name: generate github-contribution-grid-snake.svg
        if: github.event.schedule == '0 */6 * 9,10,11 *' || ((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && contains('09 10 11', env.CRL_MONTH))
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ vars.COMMIT_USERNAME }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#B6C7AA&color_dots=#EAEDF0,#FFEE4A,#FFC401,#FE9601,#02001C
            dist/github-contribution-grid-snake-dark.svg?color_snake=#E7EFF3&color_dots=#161b22,#631c03,#bd561c,#fa7a17,#fddf67

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist
          commit_message: "chore: 🐍 update snk"
          target_branch: snk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
